# name of our action
name: 'Chromatic'
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn test
      - uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          projectToken: 2wix88i1ziu
          token: ${{ secrets.GITHUB_TOKEN }}